server:
  port: 8080
spring:
  application:
    name: wind-test
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://192.168.1.158:5432/ratel?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: postgres123!
    driver-class-name: org.postgresql.Driver
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000000
      maxEvictableIdleTimeMillis: 30000000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  以下开启不能和多条语句执行并存
      # filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        # allow: 127.0.0.1,192.168.1.250
        # IP黑名单 (存在共同时，deny优先于allow)
        # deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        # login-username: admin
        # 登录密码
        # login-password: 123456
  redis:
    host: 192.168.1.158
    port: 6379
    timeout: 6000
    database: 3
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
        max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
      shutdown-timeout: 100ms
  swagger:
    enable: true
logging:
  level:
    root: info
    io.github.ramerf.wind: debug
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    log4j.logger.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    jdbc.sqltiming: info
wind:
  logic-delete-field: isDelete  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
  # 逻辑未删除值(默认为 false)
  logic-not-delete: false
  # 逻辑已删除值(默认为 true)
  logic-deleted: true
  entity-package: io.github.ramerf.wind..demo.entity.pojo
  snowflake-prop:
    worker-id: 3
    data-center-id: 2
