name: Sync Github Repos To Gitee
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Repos To Gitee #名字随便起
        uses: Yikun/hub-mirror-action@v1.0 #使用Yikun开发的hub-mirror-action
        with:
          src: github/ramerf #源端账户名
          dst: gitee/ramer #目的端账户名
          dst_key: ${{secrets.GITEE_PUB_KEY}} #SSH密钥对中的私钥，即 id_rsa
          dst_token: ${{secrets.GITEE_TOKEN}} #Gitee账户的私人令牌
          account_type: user #账户类型
          clone_style: "ssh" #使用ssh方式进行clone，也可以使用https
          debug: true #启用后会显示所有执行命令
          force_update: true #启用后，强制同步，即强制覆盖目的端仓库
          static_list: "wind" #静态同步列表，在此填写需要同步的仓库名称，可填写多个
          timeout: '600s' #git超时设置，超时后会自动重试git操作